// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDip5rMgjpwdpoe6HU-coRQJ1M3424MMvY',
    appId: '1:133940406792:web:13bd6883a72a1e0161bfbd',
    messagingSenderId: '133940406792',
    projectId: 'kanshare-ba86b',
    authDomain: 'kanshare-ba86b.firebaseapp.com',
    databaseURL: 'https://kanshare-ba86b-default-rtdb.firebaseio.com/',
    storageBucket: 'kanshare-ba86b.appspot.com',
    measurementId: 'G-YKWFHKZ5RH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoeIRrkYQkFaBQMVmaZjwoQG08v9T_DFk',
    appId: '1:133940406792:android:4cb9a26ac4d8e51561bfbd',
    messagingSenderId: '133940406792',
    projectId: 'kanshare-ba86b',
    storageBucket: 'kanshare-ba86b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaaK9lGuQ086mAaoFZd2EL7K6qhLatf-A',
    appId: '1:133940406792:ios:9b7c9c84829638fa61bfbd',
    messagingSenderId: '133940406792',
    projectId: 'kanshare-ba86b',
    storageBucket: 'kanshare-ba86b.appspot.com',
    iosBundleId: 'com.mlabs.kanshare.kanshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaaK9lGuQ086mAaoFZd2EL7K6qhLatf-A',
    appId: '1:133940406792:ios:9b7c9c84829638fa61bfbd',
    messagingSenderId: '133940406792',
    projectId: 'kanshare-ba86b',
    storageBucket: 'kanshare-ba86b.appspot.com',
    iosBundleId: 'com.mlabs.kanshare.kanshare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDip5rMgjpwdpoe6HU-coRQJ1M3424MMvY',
    appId: '1:133940406792:web:dd764352ac5abe0a61bfbd',
    messagingSenderId: '133940406792',
    projectId: 'kanshare-ba86b',
    authDomain: 'kanshare-ba86b.firebaseapp.com',
    storageBucket: 'kanshare-ba86b.appspot.com',
    measurementId: 'G-FY2W3FFFCT',
  );
}
